<<<<<<< HEAD
=======
export const FETCH_COUNTRIES = "FETCH_COUNTRIES";

>>>>>>> 4ef112532783233cffdae3089a813c5907d30f37
export const FETCH_COUNTRIES_PENDING = "FETCH_COUNTRIES_PENDING";
export const FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS";
export const FETCH_COUNTRIES_ERROR = "FETCH_COUNTRIES_ERROR";

<<<<<<< HEAD
export const FETCH_BOOKS_PENDING = "FETCH_BOOKS_PENDING";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_ERROR = "FETCH_BOOKS_ERROR";

export const FETCH_PENDING = "FETCH_PENDING";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";
=======
export const FETCH_BOOKS = "FETCH_BOOKS";

export const FETCH_BOOKS_PENDING = "FETCH_BOOKS_PENDING";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_ERROR = "FETCH_BOOKS_ERROR";
>>>>>>> 4ef112532783233cffdae3089a813c5907d30f37
