export const FETCH_COUNTRIES = "FETCH_COUNTRIES";

export const FETCH_COUNTRIES_PENDING = "FETCH_COUNTRIES_PENDING";
export const FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS";
export const FETCH_COUNTRIES_ERROR = "FETCH_COUNTRIES_ERROR";

export const FETCH_BOOKS = "FETCH_BOOKS";

export const FETCH_BOOKS_PENDING = "FETCH_BOOKS_PENDING";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_ERROR = "FETCH_BOOKS_ERROR";